window.DIAGNOSTIC = {
  session: "2026-equations",
  storageKey: "diagnostic-equations-2026-r1",
  schema: "diagnostic-equations-r1-v1",
  titre: "Manipulation d’équations",
  formation: "BTS Maintenance des systèmes — option SP",
  dureeSec: 40 * 60,
  appsScriptUrl: "https://script.google.com/macros/s/AKfycbztApl1OcZeeZJEpafIorn6uw0bDQLmyHuiAogn7ZvKvCM86YDZytCHWhay_Yp3fhISBg/exec",
  localCollecteUrl: "http://127.0.0.1:8789/",
  groupes: [
    { id: "1MS-A", label: "1MS-A — 1re année, initiale" },
    { id: "1MS-B", label: "1MS-B — 1re année, initiale" },
    { id: "1MS-ALT", label: "1MS-ALT — 1re année, alternance" },
    { id: "2MS-A", label: "2MS-A — 2e année, initiale" },
    { id: "2MS-B", label: "2MS-B — 2e année, initiale" },
    { id: "2MS-ALT", label: "2MS-ALT — 2e année, alternance" },
  ],
  bacs: [
    { id: "bac_pro_mei", label: "Bac pro MEI / MSPC (maintenance)" },
    { id: "bac_pro_indus", label: "Bac pro industriel (autre)" },
    { id: "sti2d", label: "STI2D" },
    { id: "general", label: "Bac général" },
    { id: "autre", label: "Autre / reconversion" },
  ],
  labels: {
    alaise: "À l’aise",
    construction: "En construction",
    prioritaire: "Prioritaire",
  },
};
